# Generated by Django 2.1.3 on 2018-11-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='name',
            field=models.CharField(default='胡萝卜', max_length=16),
            preserve_default=False,
        ),
    ]
