# Generated by Django 2.1.3 on 2018-11-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='memo',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
