# Generated by Django 2.1.3 on 2018-11-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_book_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordetall',
            name='age',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
    ]
